version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BeATiger
      MYSQL_DATABASE: todolist
      MYSQL_USER: tiger
      MYSQL_PASSWORD: AGoodPassword
    ports:
      - "4955:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: BeATiger
    depends_on:
      - mysql

volumes:
  mysql_data: